apiVersion: apps/v1
kind: Deployment
metadata:
  name: YouTube-Skitt-app
  labels:
    app: YouTube-Skitt-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: YouTube-Skitt-app
  template:
    metadata:
      labels:
        app: YouTube-Skitt-app
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: YouTube-Skitt-app
        image: mshow1980/YouTube-Skit:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000
