apiVersion: v1
kind: Service
metadata:
  name: YouTube-Skit-app
  labels:
    app: YouTube-Skit-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: YouTube-Skit-app
